export const TOGGLE_CHECK='TOGGLE_CHECK'
export const DELETE_TODO='DELETE_TODO'
export const ADD_TODO='ADD_TODO'
export const MOVE_UP='MOVE_UP'
export const MOVE_DOWN='MOVE_DOWN'
export const EDIT_TODO='EDIT_TODO'
export const CANCEL_EDIT='CANCEL_EDIT'